/**
 * Stable, machine-readable error codes owned by this service.
 */
export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',

  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',

  PROVIDER_NOT_FOUND: 'PROVIDER_NOT_FOUND',
  PROVIDER_ALREADY_EXISTS: 'PROVIDER_ALREADY_EXISTS',
  PROVIDER_SLUG_ALREADY_EXISTS: 'PROVIDER_SLUG_ALREADY_EXISTS',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  INVALID_VERIFICATION_TRANSITION: 'INVALID_VERIFICATION_TRANSITION',

  SKILL_NOT_FOUND: 'SKILL_NOT_FOUND',
  SKILL_INACTIVE: 'SKILL_INACTIVE',
  SKILL_SLUG_ALREADY_EXISTS: 'SKILL_SLUG_ALREADY_EXISTS',

  SERVICE_OFFERING_NOT_FOUND: 'SERVICE_OFFERING_NOT_FOUND',
  SERVICE_OFFERING_ALREADY_EXISTS: 'SERVICE_OFFERING_ALREADY_EXISTS',
  UPSTREAM_SERVICE_NOT_FOUND: 'UPSTREAM_SERVICE_NOT_FOUND',
  UPSTREAM_SERVICE_INACTIVE: 'UPSTREAM_SERVICE_INACTIVE',
  UPSTREAM_SERVICE_UNAVAILABLE: 'UPSTREAM_SERVICE_UNAVAILABLE',
  UPSTREAM_SERVICE_TIMEOUT: 'UPSTREAM_SERVICE_TIMEOUT',

  SERVICE_AREA_NOT_FOUND: 'SERVICE_AREA_NOT_FOUND',
  SERVICE_AREA_ALREADY_EXISTS: 'SERVICE_AREA_ALREADY_EXISTS',

  AVAILABILITY_SLOT_OVERLAP: 'AVAILABILITY_SLOT_OVERLAP',
  AVAILABILITY_OVERRIDE_NOT_FOUND: 'AVAILABILITY_OVERRIDE_NOT_FOUND',

  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
